import React, {Component} from 'react';
import {Platform} from 'react-native';
import ScaleSheet from 'react-native-scalesheet';

export const styles = ScaleSheet.create({
MainContainer: {
        flex: 1,
        height:'100vh',
        width:'100vw',
        backgroundColor: 'white',
        paddingTop: Platform.OS === 'ios' ? 20 : 0,
      },
      _btnSubmit: {
        height: 50,
        alignSelf: 'center',
        width: '70%',
        backgroundColor: '#203354',
        borderRadius: 27,
        margin: 25,
        fontSize: 16,
        justifyContent: 'center',
        alignItems: 'center',
      },
      _numberInput: {
        height: 50,
        alignSelf: 'center',
        width: '70%',
        marginTop: 40,
        textAlign: 'center',
        backgroundColor: '#ffffff00',
        borderRadius: 27,
        borderColor: 'lightgray',
        borderWidth: 2,
        paddingLeft: 10,
        fontSize: 18,
        marginHorizontal: 20,
        color: '#203354',
      },
      _passwordInput: {
        height: 50,
        alignSelf: 'center',
        width: '70%',
        marginTop: 25,
        textAlign: 'center',
        backgroundColor: '#ffffff00',
        borderRadius: 27,
        borderColor: 'lightgray',
        borderWidth: 2,
        paddingLeft: 10,
        fontSize: 18,
        marginHorizontal: 20,
        color: '#203354',
      },
      textFitClub:{
        marginTop: 120,
        textAlign: 'center',
        fontSize: 50,
        color: 'black',
        fontWeight: 'bold',
      },
      textFHH:{
        marginTop: 5,
        textAlign: 'center',
        fontSize: 25,
        color: '#203354',
        fontWeight: 'normal',
      },
      textUserLogin:{
        marginTop: 50,
        textAlign: 'center',
        fontSize: 20,
        color: '#203354',
        fontWeight: 'bold',
      },
      textDHA:{
        fontSize: 18,
        color: 'black',
        fontWeight: 'normal',
        alignContent: 'flex-start',
        marginLeft: 20,
      },
      textSignup:{
        fontSize: 18,
        color: '#203354',
        fontWeight: 'bold',
        alignContent: 'flex-start',
        marginTop: 5,
        marginLeft: 20,
      }
});